apiVersion: apps/v1
kind: Deployment
metadata:
  name: memex-service
  labels:
    component: memex-service
spec:
  selector:
    matchLabels:
      component: memex-service
  template:
    metadata:
      name: memex-service
      labels:
        component: memex-service
    spec:
      containers:
      - name: memex-service
        image: ${MEMEX_SERVICE_DOCKER_IMAGE_AND_TAG}
        imagePullPolicy: Always
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "prod"
        - name: "MONGO_HOST"
          value: "${MONGO_HOST}"
        - name: "MONGO_PORT"
          value: "27017"
        - name: "ELASTICSEARCH_HOST"
          value: "${ELASTICSEARCH_HOST}"
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        - name: "TOKEN_ENC_KEY_SECRET"
          value: "${TOKEN_ENC_KEY_SECRET}"
        - name: "USERPASS_ENC_KEY_SECRET"
          value: "${USERPASS_ENC_KEY_SECRET}"
