apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: dev@matthewjohnson42.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    # this selector may not be needed; todo remove if successful on next valid run
      - selector:
          dnsNames:
            - 'personal-memex-service.matthewjohnson42.com'
            - 'memex.matthewjohnson42.com'
        http01:
          ingress:
            class: nginx