apiVersion: v1
kind: Service
metadata:
  name: memex-ui-svc
  labels:
    component: memex-ui
spec:
  ports:
    - port: 4200
      targetPort: 4200
  clusterIP: ${UI_HOST}
  selector:
    component: memex-ui
