apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  labels:
    component: memex-elasticsearch
spec:
  ports:
    - name: "9200-svc"
      port: 9200
      targetPort: 9200
    - name: "9300-svc"
      port: 9300
      targetPort: 9300
  clusterIP: ${ELASTICSEARCH_HOST}
  selector:
    component: memex-elasticsearch

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    component: memex-elasticsearch
spec:
  capacity:
    storage: 4097M
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/es
  storageClassName: microk8s-hostpath
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    component: memex-elasticsearch
spec:
  volumeName: elasticsearch-pv
  storageClassName: microk8s-hostpath
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 4097M
