apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    name: memex-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: ${MONGO_HOST}
  selector:
    component: memex-mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    component: memex-mongo
spec:
  capacity:
    storage: 4097M
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
  storageClassName: microk8s-hostpath
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    component: memex-mongo
spec:
  volumeName: mongo-pv
  storageClassName: microk8s-hostpath
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 4097M
