apiVersion: apps/v1
kind: Deployment
metadata:
  name: professional-website
spec:
  selector:
    matchLabels:
      component: professional-website
  template:
    metadata:
      labels:
        component: professional-website
    spec:
      containers:
        - name: professional-website
          image: localhost:32000/professional-website:0.0.1
          imagePullPolicy: Always
