apiVersion: apps/v1
kind: Deployment
metadata:
  name: memex-ui
spec:
  selector:
    matchLabels:
      component: memex-ui
  template:
    metadata:
      labels:
        component: memex-ui
    spec:
      containers:
      - name: memex-ui
        image: ${MEMEX_UI_DOCKER_IMAGE_AND_TAG}
        imagePullPolicy: Always
